theme: jekyll-theme-minimal
title: Songnan Lin
description: <p><b>Research Fellow </b><br>School of Electrical and Electronic Engineering(EEE) <br>Nanyang Technological University, Singapore</p>
email: rainforestf0306@126.com
show_downloads: false
logo: images/songnan.png
