theme: jekyll-theme-minimal
title: Songnan Lin
description: <p><b>Ph. D. student </b><br>School of Optics and Photonics <br>Beijing Institute of Technology, China</p>
email: rainforestf0306@126.com
show_downloads: false
logo: images/songnan.png
